# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  majorVersion: 3
  minorVersion: 99
  myBuildId: $[counter('', 1)]
  revision: 1
  outputDirectory: '$(Build.SourcesDirectory)\bin\$(buildConfiguration)'
  myBuildName: $(majorVersion).$(minorVersion).$(myBuildId).$(revision)
  name: '$(majorVersion).$(minorVersion).$(myBuildId)'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '$(majorVersion).$(minorVersion).$(myBuildId)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: 'Copy built files from $(outputDirectory) to $(Build.ArtifactStagingDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(myBuildName).zip'
    replaceExistingArchive: true

- publish: $(Build.ArtifactStagingDirectory)
  displayName: 'Publish IOM $(myBuildName)'
  artifact: Binaries