# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  majorVersion: 3
  minorVersion: 99
  myBuildId: $[counter('', 1)]
  revision: 1
  outputDirectory: '$(Build.SourcesDirectory)\bin\$(buildConfiguration)\net45'
  myBuildName: $(majorVersion).$(minorVersion).$(myBuildId).$(revision)
  name: '$(majorVersion).$(minorVersion).$(myBuildId)'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '$(majorVersion).$(minorVersion).$(myBuildId)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
    Write-Host "Using an input-macro works: $(outputDirectory)"

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    maximumCpuCount: true
    logProjectEvents: false


#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  displayName: 'Archiving files $(outputDirectory) to $((Build.ArtifactStagingDirectory)/$(myBuildName).7z)'
  inputs:
    rootFolderOrFile: '$(outputDirectory)'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(myBuildName).7z'
    replaceExistingArchive: true

#- task: CopyFiles@2
#  enabled: true
#  displayName: 'Copy built files from $(outputDirectory) to $(Build.ArtifactStagingDirectory)'
#  inputs:
#    SourceFolder: '$(outputDirectory)'
#    Contents: |
#      **\?(*.exe|*.dll|*.db|*.config|*.chm|*.pdf)
#      !**\?(UT_*|AT_*)
#    TargetFolder: '$(Build.ArtifactStagingDirectory)'
#    CleanTargetFolder: true

- publish: $(outputDirectory)
  displayName: 'Publish IOM $(myBuildName)'
  artifact: Binaries